import { AxiosError } from "axios";


export const errorInterceptor  = (error: AxiosError) => {

    if(error.message === 'Network Error'){
        return Promise.reject( new Error('Error de conex√£o'));
    }

    return Promise.reject(error);

};

